### ISSUE TITLE
More colour contrast between posts and the app background

### ISSUE THREAD

**Issue by ShadowJonathan** [buresdv/Mlem#109]
cc @WestonHanners

**Comment by buresdv** [comment]
Will be solved by new post design being worked on by @EricBAndrews

**Comment by WestonHanners** [comment]
This issue was related to dark mode. The user prefers Light content on Dark over Dark content on Light.

![background contrast](https://github.com/buresdv/Mlem/assets/864259/6e64a721-0ca2-438a-9b10-42c67d1bce10)

**Comment by WestonHanners** [comment]
This was intentional to create extra contrast for the text. closing this for now.
