### ISSUE TITLE
Support for iOS 15

### ISSUE THREAD

**Issue by qeeg** [buresdv/Mlem#140]
I have an iPhone 7, which doesn't support iOS 16, but I need a Lemmy client for my phone. I can't afford a new phone and iOS 15 is still supported by most apps. I don't know why this app requires iOS 16, and it's kind of unfair to those of us on older phones.

**Comment by sirnacnud** [comment]
> @ShadowJonathan you can switch the build target to iOS 15 and see where the errors are.
> 
> Nevertheless, iOS 15 will not be supported.

I took a quick look, and there were some `URL` APIs that were easy to use the older APIs for less than iOS 16, but the main issue is the use of `NavigationStack` which is a SwiftUI iOS 16 API. This would be more work to support on iOS 15.
