### ISSUE TITLE
Proposal for Consistent Design Language and Mockups

### ISSUE THREAD

**Issue by teflocarbon** [buresdv/Mlem#141]
## Introduction
Mlem has gotten a lot of interest by various parties due to a certain site falling flat on it's face. Because of this, there has been a positive trend in pull requests for developing this app. However, one thing that has struck out to me personally is that there is currently a lack of vision in relation to a consistent design.

## Requirements
There should be a discussion on what design language to use and mockups that incorporate not only specific views like the community view, but go into detail about how UI elements should look, what colours they use, fonts and more.
There is already a mockup for the community view cards and this is a positive start, however, more is needed to ensure that the design language can remain consistent.

## Discussion
Right now, we're getting a number of PR's from users with different design experience or their own ideas. There isn't anything inherently wrong with this and it makes sense that these developers are coming up with their own designs. However, it does create a negative experience for the user of the app and discontinuity should be avoided throughout the app.
For instance, with #133, we can see the design language shift away from the current very minimalistic design to something more utilitarian, even moving away from the Figma mockup. Then we've got #124 which keeps the minimalist design, whilst introducing new display views.

As an app naturally progresses, the interface will of course have adjustments made to it. This is simply natural progression of ideas and modifications required to implement them. However, it's important to have a baseline mark that developers can look at and understand what they should follow.

Another example of this is #66, whilst I of course appreciate the contribution that they have made. The design of the pop-ups feels very un-Apple, as @buresdv puts it "I can't put my finger on it, but this makes me think of a ported Android app :("

I agree with this sentiment, but I'm not surprised that it occurred as there is no specific language for the developer to follow. They're simply going by their own accord and this is to be expected when there is no such template for them to work from. This is why I have made this proposal to work on a design language document and potentially a UI kit which can be followed and has the expectation for PR's that it will be followed.

## What I Need
As with any open source project that incorporates a user interface, it's crucial that we address the needs and considerations of users, and take their feedback into account. Design is subjective and requires careful deliberation to ensure a consistent, user-friendly experience.

I want to make it clear that I am not criticizing the hard work of contributors. Instead, I aim to address a challenge we face collectively and find a way to enhance the consistency of our design efforts to ensure that users receive the native experience that they expect.

I suggest we initiate a community-wide discussion on the proposed design language, start gathering ideas, and find propose who can lead the effort to create a comprehensive design document. I'm looking forward to your thoughts and suggestions on this proposal.

And lastly, thank you to everyone who contributes their time and skills to this project. Let's continue to make Mlem a better experience for all.

**Comment by ShadowJonathan** [comment]
We are currently getting a lot of new contributors who submit their PRs based on their own idea of how to form the app, we're currently getting a lot of attention right now.

@buresdv holds the last say over the design of the app, and internally we have a figma team and mockups where we keep the design of the app consistent. We're aiming to be like Apollo in terms of UX, but also in terms of UI, which means that we try to be as consistent to Apple's design language as possible.

The PRs you mentioned havent been merged or accepted yet, personally, i'd find this feedback to a lot more striking or appropriate if multiple PRs were merged that had inconsistent design, but this has (as far as i know) not happened.

Your concern is applicable, however, and appreciated, but I'll be closing this issue as right now - from my perspective - it looks to be going the right direction as you are proposing here.

Not everyone is a designer, and while users can and will have feedback on UI elements that're confusing or frustrating, that feedback pipeline is already sort-of established via the testflight screenshot and feedback system. We also have people experienced in design, currently, participating in that discussion, with also a focus on accessibility.

We have a matrix Space which you can join, to continue this discussion: https://matrix.to/#/#mlemapp:matrix.org
