### ISSUE TITLE
Remove the messages tab for the time being

### ISSUE THREAD

**Issue by PumpedSardines** [buresdv/Mlem#150]
## Introduction
I got really confused over what the messages tab was meant to do when first downloading the app, when looking at the code it doesn't seem to do anything other than displaying the username and id. Maybe we should comment out that tab or write a text explaining that messages will be a feature soon instead of displaying dummy text?

## Requirements
Comment out line 27 to 30 in `ContentView.swift`

**Comment by buresdv** [comment]
This tab will be used soon, so it should not be removed.
