### ISSUE TITLE
Support for older iOS Releases

### ISSUE THREAD

**Issue by mr-cringe61** [buresdv/Mlem#159]
Might be a bit optimistic but I bassically want support for older iOS versions. iOS 15.4 and above would be fine for me, but much ealier versions are also appreciated. No one should be forced to update the iOS version or the device. Especially if you are into Jailbreaking (like me). I would appreciate the change but have to understand if it’s not possible. Thank you anyways :)

**Comment by buresdv** [comment]
Unfortunately not possible, I'm sorry #140

**Comment by mr-cringe61** [comment]
It IS possible. You just chose to not rewrite the app without the iOS 16 exclusive APIs. Anyways, guess not everyone will be able to use the app. Thanks for your reply ;)

**Comment by mr-cringe61** [comment]
An exported .ipa would be useful though.
