### ISSUE TITLE
Clarify license in the README

### ISSUE THREAD

**Issue by fwcd** [buresdv/Mlem#170]
The README states that

https://github.com/buresdv/Mlem/blob/344fe0c91966fdf7ff465ccdaac6f7f1ebd8cdc5/README.md#L9

https://github.com/buresdv/Mlem/blob/344fe0c91966fdf7ff465ccdaac6f7f1ebd8cdc5/README.md#L48-L50

This is however not entirely correct, Commons Clause is a license that (when applied to an OSS license, probably a good idea to specify the base license too) makes a project [source-available](https://en.wikipedia.org/wiki/Source-available_software), but _not_ [open-source](https://en.wikipedia.org/wiki/Open-source_software), the latter has a pretty specific definition that e.g. [cannot forbid commercial use](https://opensource.stackexchange.com/questions/9805/can-i-license-my-project-with-an-open-source-license-but-disallow-commercial-use).

**Comment by ShadowJonathan** [comment]
"Open source" is when the source is open.

The source is open, we just specify its not open for other businesses to take our app and commercialise it for themselves with no regard for our work.

**Comment by ShadowJonathan** [comment]
I also think the Commons Clause itself is fairly clear on this point as well;

![image](https://github.com/buresdv/Mlem/assets/22740616/8e23cedd-1209-4e34-a4fa-8e1c0a8aa461)

**Comment by fwcd** [comment]
> "Open source" is when the source is open.

I am afraid not. You may want to read up on the FAQ of the Commons Clause:

<img width="357" alt="image" src="https://github.com/buresdv/Mlem/assets/30873659/cddb8a0b-a285-4d55-9ffa-dd0bef7b8aa9">

Using the Commons Clause is a perfectly valid choice of license, but please don't call it "open source", since that is incorrect and also confuses users, given that the term has a precise definition and users consequentially expect certain freedoms from that.

**Comment by ShadowJonathan** [comment]
It will only maybe confuse developers for a moment, the regular user doesn't even know open source exists, much less a precise definition.

**Comment by ShadowJonathan** [comment]
We will do the latter.
