### ISSUE TITLE
Duplicate posts being added to feed

### ISSUE THREAD

**Issue by mormaer** [buresdv/Mlem#179]
In some cases we are still ending up with duplicate posts in our `PostTracker` which is highlighted in Xcode by SwiftUI complaining that there are non-unique ids present in the view.

The posts themselves are identified by their id from the API and after discussion with @ShadowJonathan it's been agreed that these are uniquely identifying, this means the error is somewhere on our side.

There was a similar issue (https://github.com/buresdv/Mlem/issues/69) that has been resolved. In that case there were multiple calls being triggered for the same page, which has been resolved.

More investigation is needed to find where/how we're making a similar error.

**Comment by WestonHanners** [comment]
@mormaer, I don't think #69 was fixed, I am still seeing duplicate API calls with the same page number on master.
The Page Tracker seems to be doing the right thing. I am not sure where the issue is yet.
