### ISSUE TITLE
* cross posts don't include original captions 

### ISSUE THREAD

**Issue by jenkshields** [buresdv/Mlem#187]
**Describe the bug**
What did you do to trigger the bug?

Cross-posts don't include original captions - potentially just ones with images? 

This post is a good example - in mlem all i see if the logo. https://lemmy.dbzer0.com/post/36148

**Mlem Information:**
Version 0.0.7, 23
Pretty sure 23 introduced this bug 

**Additional Context**
Any other relevant information

**Comment by mormaer** [comment]
Thanks for the report - resolved in #174
