### ISSUE TITLE
Reply shows 2h age despite being new

### ISSUE THREAD

**Issue by chrismarquardt** [buresdv/Mlem#19]
Might be some time zone mismatch or some thing. Maybe UTC instead of local time zone?

![IMG_3265](https://github.com/buresdv/Mlem/assets/2527608/bcc2bc7d-ea77-4655-a0f3-f49cca78c023)

**Comment by buresdv** [comment]
Maybe related to #6

**Comment by buresdv** [comment]
Will be fixed in the next release:
![IMG_E216990B4CC3-1](https://github.com/buresdv/Mlem/assets/22037369/e8652fe1-a091-4a9f-8e9a-8f9a797a4490)
