### ISSUE TITLE
* Useless items in settings

### ISSUE THREAD

**Issue by bolshoytoster** [buresdv/Mlem#190]
**Describe the bug**
What did you do to trigger the bug?

Went to the settings app > Mlem

**Expected Behavior**
What did you expect to happen?

Not much should be there

**Actual Behavior**
What actually happened?

There are some items, none of them do anything, so were probably just to test something.

**To Reproduce**
What steps do I need to take to trigger the bug?

Go to the settings app > Mlem

**Mlem Information:**
Version + Build number
If this started happening recently, write which version introduced the bug

It's caused by `Mlem/Settings.bundle/Root.plist`, added in a commit about 1 year ago.

**Additional Context**
Any other relevant information

**Comment by ShadowJonathan** [comment]
Please be specific, which settings "don't do anything"?

**Comment by bolshoytoster** [comment]
@ShadowJonathan the ones in the settings app:
![image](https://github.com/buresdv/Mlem/assets/91278344/18c331bc-a020-4131-a0ca-a3cff6bdee59)
