### ISSUE TITLE
Can’t undo upvotes

### ISSUE THREAD

**Issue by ianonavy** [buresdv/Mlem#191]
**Describe the bug**
What did you do to trigger the bug?

Press the upvote button on a post two times in a row 

**Expected Behavior**
What did you expect to happen?

I expected the upvote to clear after the second press

**Actual Behavior**
What actually happened?

Pressing the upvote button the second time had no effect unless I refreshed the feed. 

**To Reproduce**
What steps do I need to take to trigger the bug?

1. Navigate to Feeds
2. Upvote a post
3. Click the upvote button again on the same post

**Mlem Information:**
Version + Build number
If this started happening recently, write which version introduced the bug

Can’t find the version in the about page to confirm but I just updated and I think it’s 0.0.7

**Additional Context**
Any other relevant information

Thanks for making a great app!

**Comment by ShadowJonathan** [comment]
You might be hitting the absence of https://github.com/buresdv/Mlem/issues/117; currently the score button is "locked" until the request to upvote goes through, we update the local score immediately, but it might take a moment or two to actually be requested by the API.

**Comment by ianonavy** [comment]
I agree it is related. It does seem like eventually it goes through, or occasionally the request will fail and I see in the error logs ["failed to vote!"](https://github.com/buresdv/Mlem/blob/314fc8ee405b805eda263fd0cf6979ce72618543/Mlem/Views/Tabs/Posts/Components/Post/Components/Community%20View/Post%20Item/Feed%20Post.swift#L76)

I stepped through the post interaction bar logic, and it does seem like when the API request hangs [this line](https://github.com/buresdv/Mlem/blob/314fc8ee405b805eda263fd0cf6979ce72618543/Mlem/Views/Tabs/Posts/Components/Post/Components/Community%20View/Post%20Item/Components/Post%20Interaction%20Bar.swift#L167) is never reached.

**Comment by ShadowJonathan** [comment]
We should probably set that line in a `try-finally` catch, but we're already planning to replace this with a more robust and clean abstraction, so I question what the usefulness of that would be here.
