### ISSUE TITLE
Upvoting comments does not work

### ISSUE THREAD

**Issue by pJunger** [buresdv/Mlem#21]
After updating to 0.0.6 (17) I cannot up or downvote on comments anymore. The buttons do not seem to register at all.
Voting on the corresponding post works though.

**Comment by buresdv** [comment]
Thank you for the report! This will be fixed in today's update, see #22

**Comment by buresdv** [comment]
The hotfix is out now: https://elk.zone/mstdn.social/@davidbures/110485874851125451
