### ISSUE TITLE
Subscribed communities not shown

### ISSUE THREAD

**Issue by socphoenix** [buresdv/Mlem#3]
Using the web interface I’ve subscribed to a few communities both on my main server and others, but on the app I’m only shown what’s local to my server. Is there a way to add these in to the app?

**Comment by buresdv** [comment]
An update will come out later today that will default the feed to showing you your subscribed communities. Make sure to keep the app up to date

**Comment by buresdv** [comment]
I will consider this issue solved since there are no new comments
