### ISSUE TITLE
Can’t login to an account 

### ISSUE THREAD

**Issue by millionsofplayers** [buresdv/Mlem#4]
I don’t have an option to log into an account. 
![IMG_6811](https://github.com/buresdv/Mlem/assets/15851867/a825764f-778e-4d7a-a82f-01c882d70da0)

**Comment by buresdv** [comment]
Damn, I have no idea how this could have happened. Do the buttons still not show up when you go into landscape mode?

**Comment by buresdv** [comment]
Never mind, I fixed it Hotfix coming out now :)
