### ISSUE TITLE
How can I get a TestFlight invitation code

### ISSUE THREAD

**Issue by Paulie420** [buresdv/Mlem#44]
Thats all.. new LemmyNet r0ckstar here.

**Comment by buresdv** [comment]
It's on Lemmy's page, go to Apps and the link is there 👍 https://join-lemmy.org/apps

**Comment by sergiodlc** [comment]
"This beta is full" 😢

**Comment by buresdv** [comment]
Yeah, unfortunately it got filled up recently :(
