### ISSUE TITLE
Replace system for creating replies

### ISSUE THREAD

**Issue by buresdv** [buresdv/Mlem#5]
## Introduction
As is it now, when you create a reply to a comment, Mlem pulls the entire feed again and then force-reloads the view by changing its ID. This is obviously not ideal.

## Requirements
This system should get replaced by appending a new comment child to a parent comment. This would be accomplished by a recursive function, which will traverse the comment tree and append the new comment to an already-existing array element that matches the new comment's `parentID`.

## Discussion
The `Comment` struct is defined as such (see [Comment.swift](https://github.com/buresdv/Mlem/blob/master/Mlem/Models/User-Interactable/Comment.swift) for complete definition:
```
struct Comment: Codable, Identifiable, Hashable
{
    static func == (lhs: Comment, rhs: Comment) -> Bool {
        lhs.id == rhs.id
    }
    
    let id: Int
    
    (...)

    let parentID: Int?

    (...)

    var children: [Comment]
}
```

The `Comment` struct has a recursive property called `children`, which holds all child comments, i.e. all replies to a particular comment.

### Comment IDs

Each comment has a property `id`. This `id` property corresponds to a child comment's property `parentID`. Top-level comments have no parents, hence why for top-level comments, `parentID` is `nil`.

Take, for example, a parent comment and its reply:
```
let parentComment: Comment = Comment(id: 10, parentID: nil)
let childComment: Comment = Comment(id: 20, parentID: 10)
```

As you can see, the `parentID` of `childComment` corresponds to the `id` of `parentComment`. This means that `childComment` is a reply to `parentComment`. Courtesy of @sebj, there is already a function for building comment trees.

### What I Need

When you post a reply to a comment, a new `Comment` gets created. This new `Comment` contains a `parentID`, denoting which comment it is a reply to. I need a function which will take the following arguments:
`func createReply(to parentComment: Comment, newComment: Comment) -> [Comment]`

This function needs to traverse the comment tree, find which `Comment` in the tree has an `id` corresponding to the new `Comment`'s `parentID` property, and then append that new comment to the parent `Comment`'s `children` array. It will then return the comment tree with the new comment inserted at the correct location.

@samalone

**Comment by samalone** [comment]
Before we get into the implementation, I'm wondering if the function should return a single Comment rather than an array. If this function is a method on the Comment struct, and it's being called on the top-level Comment, shouldn't it simply return the current (self) Comment with the additional Comment added somewhere deep in the tree?

```swift
struct Comment: Codable, Identifiable, Hashable
{
    static func == (lhs: Comment, rhs: Comment) -> Bool {
        lhs.id == rhs.id
    }
    
    let id: Int
    
    (...)

    let parentID: Int?

    (...)

    var children: [Comment]

    // Returns a copy of self with the newComment added as a child of parentComment
    func createReply(to parentComment: Comment, newComment: Comment) -> Comment
}
```

**Comment by buresdv** [comment]
That's an interesting idea. For a bit more context:
I have a `@StateObject` in the environment that stores the entire comment tree so it can get rendered. I was thinking that if it returned an array of all the comments, we could then replace the comment tree in the `@StateObject`, which would update the UI.

Do you think it could still be possible?

**Comment by samalone** [comment]
I think modifying the `@StateObject` array is not part of the recursive function. Let's write the recursive function first, and then use that to modify the `@StateObject` array.

With a recursive function, the strategy is to solve the simple cases first and then break the more complex cases down into smaller pieces that can be solved separately and combined. In this situation, the simple case is where the parentComment is `self`:

```swift
func createReply(to parentComment: Comment, newComment: Comment) -> Comment {
    if id == parentComment.id {
    	return Comment(id: id,
    	               parentID: parentID, 
    	               children: children.appending(newComment))
    }
    else {
    	// Use recursion to break the problem down into smaller problems
    	// and combine the results.
    }
}
```

If we're not in the simple case, then we pass the problem on to our children.

```swift
func createReply(to parentComment: Comment, newComment: Comment) -> Comment {
    if id == parentComment.id {
    	return Comment(id: id,
    	               parentID: parentID,
    	               children: children.appending(newComment))
    }
    else {
    	// Break the problem down into smaller problems:
    	let newChildren = children.map {
    		$0.createReply(to: parentComment, newComment: newComment)
    	}
    	// Return the combined results:
    	return Comment(id: id, 
                       parentID: parentID, 
    	               children: newChildren)
    }
}
```

Since all we really need from the parentComment is its id, and that id is already part of the newComment, we can simplify this a bit.

```swift
func createReply(newComment: Comment) -> Comment {
    if id == newComment.parentID {
    	return Comment(id: id,
    	               parentID: parentID,
    	               children: children.appending(newComment))
    }
    else {
    	// Break the problem down into smaller problems:
    	let newChildren = children.map {
    		$0.createReply(newComment: newComment)
    	}
    	// Return the combined results:
       return Comment(id: id, 
                       parentID: parentID, 
    	               children: newChildren)
    }
}
```

Once you have this function, you can modify the `@StateObject` array with:

```swift
commentTree = commentTree.map { $0.createReply(newComment: newComment) }
```

**Comment by samalone** [comment]
There's one more special case that might be worth optimizing: If we are not the parent, and we have no children, then we can simply return `self` unmodified.

```swift
func createReply(newComment: Comment) -> Comment {
    if id == newComment.parentID {
    	return Comment(id: id,
    	               parentID: parentID,
    	               children: children.appending(newComment))
    }
    else if children.isEmpty {
        return self
    }
    else {
    	// Break the problem down into smaller problems:
    	let newChildren = children.map {
    		$0.createReply(newComment: newComment)
    	}
    	// Return the combined results:
        return Comment(id: id, 
                       parentID: parentID, 
    	               children: newChildren)
    }
}
```

**Comment by buresdv** [comment]
That's very clever! I'd never be able to come up with this myself 😅 

Would you be willing to implement this function and do a PR? Just the function itself, I can implement the `@StateObject` replacing.

**Comment by samalone** [comment]
Sure. Take a look at https://github.com/buresdv/Mlem/pull/7

**Comment by buresdv** [comment]
It worked perfectly! Thank you so much, this has caused me so many headaches, I can't be grateful neough! Are you accepting apprentices? 😂
