### ISSUE TITLE
Comment Toolbar Revision

### ISSUE THREAD

**Issue by Guy-Dudeman** [buresdv/Mlem#53]
Hi there!
I've noticed that on the desktop gui, there is plenty of room to display all the toolbar buttons, but they're hidden behind a "More..." menu:
![image](https://github.com/buresdv/Mlem/assets/136025639/298cbf8d-f04e-40e1-a075-23acd842fd31)
![image](https://github.com/buresdv/Mlem/assets/136025639/08194b1c-c4d8-4c8a-9706-0b5d80cb1f8d)

It seems like an unnecessary click for the desktop user. What's the philosophy behind it? Is it possible to just make all the icons just display instead of hiding half of them?

**Comment by Guy-Dudeman** [comment]
Sorry, meant to post this in the main lemmy project. Not mlem.

**Comment by buresdv** [comment]
No problem
