### ISSUE TITLE
Release an ipa package or support older version of iOS (iOS 15) via Testflight

### ISSUE THREAD

**Issue by dtantono** [buresdv/Mlem#58]
## Introduction
with Reddit new policy incoming, I am sure there are many people who want to join Lemmy. But, many people cannot afford new phone and their phone cannot support latest IOS

## Requirements
it will be wonderful if Mlem can cater user that have this kind of problem

## Discussion
iOS 15 still relevant worldwide https://gs.statcounter.com/os-version-market-share/ios/mobile-tablet/worldwide

## What I Need
you can release the iPA package. So, we can sideload it with trollstore or altstore or support older iOS version via testflight

**Comment by buresdv** [comment]
Thanks for the idea, and while you're not the first one who suggested this, I unfortunately have to say  thatiOS 15 will not be supported since Mlem is using iOS 16-only APIs 🙁

**Comment by ismailkarsli** [comment]
Hi @buresdv. Can you at least release an IPA file? So we wouldn't need to install an extra app.

**Comment by Dylan96** [comment]
@buresdv please reconsider ios 15 support...

**Comment by sirnacnud** [comment]
> Thanks for the idea, and while you're not the first one who suggested this, I unfortunately have to say that iOS 15 will not be supported since Mlem is using iOS 16-only APIs 🙁

What special iOS 16 APIs is it using?

**Comment by dtantono** [comment]
Hi Guys, if you use iOS 15. you can use this alternative and test it instead https://testflight.apple.com/join/6jaRU6rD
