### ISSUE TITLE
Relative age of posts and comments is off by time zone offset, showing some things in the future

### ISSUE THREAD

**Issue by mahtd** [buresdv/Mlem#6]
I noticed that the relative time for post I was looking at was “in 5”, while the website said “4h”. 7 minutes later, the app said “2 min.”

My phone is set to EDT which is 4 hours behind UTC

![IMG_1844](https://github.com/buresdv/Mlem/assets/6687627/b99d9add-efed-4a02-8e89-e996c938933b)
![IMG_1845](https://github.com/buresdv/Mlem/assets/6687627/5305f779-75ae-4b26-b07e-7b376103c71d)
![IMG_1846](https://github.com/buresdv/Mlem/assets/6687627/abcf9402-387e-487e-adf3-09d4b67cde79)

**Comment by buresdv** [comment]
Thanks for the repost, I'll look into it

**Comment by buresdv** [comment]
Is this still happening in the latest version?

**Comment by mahtd** [comment]
Nope, looks good to me now. Thanks!

![IMG_1866](https://github.com/buresdv/Mlem/assets/6687627/0cbeb1e9-712b-40a7-a4bc-ac2893823ae0)
![IMG_1867](https://github.com/buresdv/Mlem/assets/6687627/0733d256-50cd-4a4d-8ab1-806d76ed0834)
