### ISSUE TITLE
Downvotes aren't disabled when they're disabled on the instance

### ISSUE THREAD

**Issue by ShadowJonathan** [buresdv/Mlem#65]
**Describe the bug**
Currently logged in on beehaw on the app, which has downvotes disabled.

**Expected Behavior**
Downvotes to be disabled on the app too.

**Actual Behavior**
No downvotes disabled, an error when I try to downvote.

**Mlem Information:**
Version + Build number: 0.0.6 (21)

**Comment by ShadowJonathan** [comment]
Ah, then this can be closed as duplicate, this is what i get for not looking... 😬

**Comment by buresdv** [comment]
No worries 😄
