### ISSUE TITLE
crashing when clicking Universal Links

### ISSUE THREAD

**Issue by snooptodd** [buresdv/Mlem#68]
**Describe the bug**
clicked link of the format [News](/c/news@beehaw.org)

**Expected Behavior**
What did you expect to happen?
open news@beehaw.org

**Actual Behavior**
What actually happened?
app crashed

**To Reproduce**
What steps do I need to take to trigger the bug?
click a link of the above format they are easy to find in (https://lemmy.world/c/newcommunities)

**Mlem Information:**
Version + Build number
0.0.6 (21)
If this started happening recently, write which version introduced the bug
unknown

**Additional Context**
Any other relevant information
I dont know if it will happen will all links but it has happend with every link i have tried

**Comment by ShadowJonathan** [comment]
Should be worth to note that beehaw.org is down right now

**Comment by ShadowJonathan** [comment]
Beehaw is up again, @snooptodd can you confirm if it works now?

**Comment by andrew-vanderbilt** [comment]
I was unable to reproduce. It is worth noting that the code is currently riddled with try! and other nasties than will cause crashing of anything is out of order. I suspect that the failure to get a response from Beehaw might have caused it.

**Comment by snooptodd** [comment]
Sorry my original report is very poorly formatted. 
it is still happening for me. 
exact steps to reproduce

open mlem
click on the single account set up @lemmy.world
tap top where it says subscribed. 
search for "new and select newcommunities
click on any link formatted in this way `[me]/u/snooptodd@lemmy.world` 

it does not matter the instance any link clicked that is formatted that way will crash the app. 
other links work fine.

**Comment by andrew-vanderbilt** [comment]
> Sorry my original report is very poorly formatted. it is still happening for me. exact steps to reproduce
> 
> open mlem click on the single account set up @lemmy.world tap top where it says subscribed. search for "new and select newcommunities click on any link formatted in this way `[me]/u/snooptodd@lemmy.world`
> 
> it does not matter the instance any link clicked that is formatted that way will crash the app. other links work fine.

I’ll try to reproduce it tomorrow and report back.

**Comment by buresdv** [comment]
Tracked by #71

**Comment by buresdv** [comment]
Might be related to #29, as pushing onto the NavigationStack could be a solution for showing the contents of the link

**Comment by mormaer** [comment]
I've had a quick look at this and we crash because Safari doesn't like non `http`/`https` urls being passed into it.

We can avoid the crash easily enough, but I'll see if we can use something like the `resolve_object` call to determine if we can handle it natively and push into the community view or such

**Comment by noloman** [comment]
Sorry but newbie here: what's the `resolve_object`?

**Comment by ShadowJonathan** [comment]
Its one of Lemmy's APIs, with some of the following signature, which should explain what it is or what it does.

`/resolve_object`;

```rust
/// Converts search query to object id. The query can either be an URL, which will be treated as
/// ObjectId directly, or a webfinger identifier (@user@example.com or !community@example.com)
/// which gets resolved to an URL.
#[tracing::instrument(skip_all)]
pub(crate) async fn search_query_to_object_id(
```

```rust
pub struct ResolveObjectResponse {
  pub comment: Option<CommentView>,
  pub post: Option<PostView>,
  pub community: Option<CommunityView>,
  pub person: Option<PersonViewSafe>,
}
```
