### ISSUE TITLE
posts loop on any sort other than Hot

### ISSUE THREAD

**Issue by millionsofplayers** [buresdv/Mlem#69]
**Describe the bug**
What did you do to trigger the bug?
Went on a sort that’s not hot

**Expected Behavior**
What did you expect to happen?
For the posts to sort by date

**Actual Behavior**
What actually happened?
Some of them sorted by date, but most didn’t show up and instead the first few started looping

**To Reproduce**
What steps do I need to take to trigger the bug?
 - log in through beehaw (not sure if it happens on other instances)
 - Toggle on a sort other than hot in the homepage 

**Mlem Information:**
Version + Build number
Beta 0.0.6
If this started happening recently, write which version introduced the bug

**Additional Context**
Any other relevant information

**Comment by buresdv** [comment]
Fixed by #69 (nice)

**Comment by WestonHanners** [comment]
I am still seeing this in the latest master.
