### ISSUE TITLE
Mlem should provide inbox notifications

### ISSUE THREAD

**Issue by BrooklynMan** [buresdv/Mlem#82]
## Introduction
Apps that provide service which receive messages and new comment replies should provide users with notifications

## Requirements
Mlem should provide notifications of receipt of messages and new comment replies to inbox.

## Discussion
Please add the option for the app to provide notifications of inbox messages and new comment replies, possibly with options for alert tones.

## What I Need
provide notifications for inbox messages and new comment replies

**Comment by ShadowJonathan** [comment]
Duplicate of https://github.com/buresdv/Mlem/issues/45
